### ISSUE TITLE
Vereinfachung des Programmcodes

### ISSUE THREAD

**Issue by cdqwertz** [LNJ2/gWuerfeln#1]
Ich glaube du kannst Zeile 36 durch 

``` python
print("\t|".join(endResult))
```

ersetzen.
Eventuell musst du noch einmal einen Substring davon machen um das \t am Anfang zu entfernen :smile: .

PS : Mir ist grad ein wenig langweilig, deswegen hab ich mir mal diese Repo angeschaut :)

**Comment by lnjX** [comment]
Ich bekomme immer diesen Fehler...

``` python
Traceback (most recent call last):
  File "./__main__.py", line 42, in <module>
    main()
  File "./__main__.py", line 36, in main
    print("\t|".join(endResult), end="\r")
TypeError: sequence item 0: expected str instance, int found
```
